Closes
UMassCDS/inatator pull request #86
Opened 2024-09-24 17:33 UTC by oz03-hub

2024-09-26 19:21 UTC, ginic requested changes
@oz03-hub , this looks great! I tested out both using Docker and running locally and everything is working as expected for me. I really like these changes! The UI looks nicer and has better behaviour with screen resizing and I also think these changes make the code easier to follow. Really nice work! 

I noticed a couple minor things that are worth checking over. There are more details in comments, but basically it comes down to two things: 
- Are you sure we need a new package-lock.json and package.json at the root level? 
- Check the error handling between your functions in api.js and utils.js and make sure it's working in the way you expect so that it's easy to debug any errors

2024-09-26 19:26 UTC, oz03-hub commented on package-lock.json
> +{
These files should not be here, I will remove them, I guess that's why the npm i you ran placed things in the root

2024-09-27 13:50 UTC, oz03-hub commented on src/frontend/src/api.js
> +    .catch((error) => console.error("Error generating prediction:", error));
I understand, I removed catch from api functions, any error handling is done in util.js

2024-09-27 13:52 UTC, oz03-hub commented
Removed root packages (unnecessary), removed unused css, make error handling only handled by caller

2024-09-27 16:47 UTC, ginic commented on src/frontend/src/api.js
> +    .catch((error) => console.error("Error generating prediction:", error));
Thanks! The changes look good to me!

2024-09-27 16:47 UTC, ginic approved these changes
Nice work! This changes are excellent!

2024-09-28 13:40 UTC, merged